# Generated by Django 4.0.10 on 2024-03-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
