# Generated by Django 4.0.10 on 2024-03-27 10:01

from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=post.models.CharField(max_length=65000),
        ),
    ]
