# Generated by Django 4.0.10 on 2024-04-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_create_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='text_field2',
            field=models.CharField(max_length=10),
        ),
    ]
